language: c
# To build on OSX, switch the previous line to
# language: objective-c
env:
  matrix:
    - TYPE=cran
    - TYPE=cran RELEASE=trunk
    - TYPE=tests
    - TYPE=tests RELEASE=trunk
    - TYPE=tests RELEASE=tags/R-3-0-1
    - TYPE=tests RELEASE=tags/R-3-0-0
    - TYPE=tests RELEASE=tags/R-2-15-3
    - TYPE=tests RELEASE=tags/R-2-15-2
    - TYPE=tests RELEASE=tags/R-2-15-1
    - TYPE=tests RELEASE=tags/R-2-15-0
    - TYPE=tests RELEASE=tags/R-2-14-2
    - TYPE=tests RELEASE=tags/R-2-14-1
    - TYPE=tests RELEASE=tags/R-2-14-0

script:
  - if [ $TYPE == cran ]; then ./travis-tool.sh run_tests; fi
  - if [ $TYPE == tests ]; then ( cd ..; R CMD build tikzDevice; R CMD INSTALL tikzDevice*.*.tar.gz ); ( cd tests; ./unit_tests.R ); fi

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - IsSourceInstall() { [[ -n "${RELEASE}" ]]; }
  - if [ $TYPE == tests ]; then APT_EXTRA="texlive-xetex imagemagick"; export DISPLAY=:99.0; fi
  - if IsSourceInstall; then export FORCE_SOURCE_INSTALL=1; fi
install:
  - sudo apt-get install --no-install-recommends texinfo texlive-latex-recommended texlive-latex-extra lmodern texlive-fonts-recommended texlive-fonts-extra pgf $APT_EXTRA
  - if [ $TYPE == tests ]; then (cd /tmp && curl -OL http://mirrors.ctan.org/install/macros/latex/contrib/oberdiek.tds.zip && cd /usr/share/texmf/tex/latex && sudo unzip /tmp/oberdiek.tds.zip && sudo texhash); fi
  - sh -e /etc/init.d/xvfb start
  - if IsSourceInstall; then (
      cd ~ &&
      svn co -q https://svn.r-project.org/R/${RELEASE}/ r-source &&
      cd r-source &&
      tools/rsync-recommended &&
      R_BATCHSAVE="--no-save --no-restore"
        R_BROWSER=xdg-open
        PAGER=/usr/bin/pager
        PERL=/usr/bin/perl
        R_UNZIPCMD=/usr/bin/unzip
        R_ZIPCMD=/usr/bin/zip
        R_PRINTCMD=/usr/bin/lpr
        LIBnn=lib
        AWK=/usr/bin/awk
        CC=gcc
        CFLAGS="-ggdb -pipe -std=gnu99 -Wall -pedantic"
        CXX=g++
        CXXFLAGS="-ggdb -pipe -Wall -pedantic"
        FC=gfortran
        F77=gfortran
        MAKE="make -j2"
          ./configure --enable-R-shlib &&
      make -j2 &&
      sudo make install
    ); fi
  - ./travis-tool.sh r_binary_install colorspace zoo RColorBrewer dichromat munsell labeling Formula sp mvtnorm TH.data sandwich gtable reshape2 scales proto quantreg Hmisc mapproj hexbin maptools multcomp filehash ggplot2 testthat
  - ./travis-tool.sh dump_sysinfo
after_failure:
  - cat ~/r-source/config.log || true
  - cat tikzDevice.Rcheck/00install.out || true
  - cat tikzDevice.Rcheck/00check.log || true
